Fixed more containers via direct singularity pull
Original invocation was

    datalad run -m "Fix more of containers now with direct singularity pull since building using our Singularity. file seems to give head aches" duct scripts/fixup-rebuild-no-runscripts .duct/logs/2025.12.28T12.22.32-579430_stderr

but it failed due to

    FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: conveyor failed to get: writing blob: happened during read: unexpected EOF
      ERROR: Pull failed for images/bids/bids-nibabies--25.2.0.sing

I will just retry